apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-backend
  labels:
    app: ticket-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-backend
  template:
    metadata:
      labels:
        app: ticket-backend
    spec:
      containers:
        - name: ticket-backend
          image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/ticket-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AWS_REGION
              value: us-east-1
apiVersion: v1
kind: Service
metadata:
  name: ticket-backend-service
spec:
  type: NodePort
  selector:
    app: ticket-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080

