name: Build Deploy Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: ECR Login
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_BACKEND_IMAGE }}

    - name: Build & Push Backend
      run: |
        docker build -t backend ./backend/ticket-service
        docker tag backend:latest ${{ secrets.ECR_BACKEND_IMAGE }}:latest
        docker push ${{ secrets.ECR_BACKEND_IMAGE }}:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/

